
INSERT INTO shape VALUES(1, 35, 7, 8, 20);
INSERT INTO shape VALUES(2, 13, 120, 20, 100);
INSERT INTO shape VALUES(3, 30, 9, 100, 15);

INSERT INTO circle VALUES(1, 'cylinder');
INSERT INTO rectangle VALUES(2, 'rectangular prism', 20);
INSERT INTO triangle VALUES(3, 'triangular prism', 30, 29);

INSERT INTO drawing VALUES(1, 'picture1');
INSERT INTO drawing VALUES(2, 'picture2');
INSERT INTO drawing VALUES(3, 'picture3');
INSERT INTO drawing VALUES(4, 'picture4');

INSERT INTO DRAWING_LIST_SHAPE VALUES(1, 1);
INSERT INTO DRAWING_LIST_SHAPE VALUES(1, 2);
INSERT INTO DRAWING_LIST_SHAPE VALUES(1, 3);

INSERT INTO DRAWING_LIST_SHAPE VALUES(2, 1);
INSERT INTO DRAWING_LIST_SHAPE VALUES(2, 3);

INSERT INTO DRAWING_LIST_SHAPE VALUES(3, 2);
INSERT INTO DRAWING_LIST_SHAPE VALUES(3, 3);

INSERT INTO DRAWING_LIST_SHAPE VALUES(4, 1);
INSERT INTO DRAWING_LIST_SHAPE VALUES(4, 2);
